export const answer = [
  { _id: '1', questionId: '1', answer: 'Test avafsa', isCorrect: false },
  { _id: '2', questionId: '1', answer: 'Test avafsa asdasd', isCorrect: true },
  { _id: '3', questionId: '1', answer: 'Test 65321', isCorrect: false },
  { _id: '4', questionId: '1', answer: 'Test avitoi', isCorrect: false },
  { _id: '5', questionId: '2', answer: 'Trong Javascript sự kiện OnUnload thực hiện khi', isCorrect: false },
  { _id: '6', questionId: '2', answer: 'Trong Javascript sự kiện', isCorrect: false },
  { _id: '7', questionId: '2', answer: 'Trong Javascript sự kiện OnUnload', isCorrect: true },
  { _id: '8', questionId: '2', answer: 'Trong Javascript', isCorrect: false },
  { _id: '1', questionId: '3', answer: 'Test avafsa', isCorrect: true },
  { _id: '2', questionId: '3', answer: 'Test avafsa asdasd', isCorrect: false },
  { _id: '3', questionId: '3', answer: 'Test 65323', isCorrect: false },
  { _id: '4', questionId: '3', answer: 'Test avitoi', isCorrect: false },
  { _id: '5', questionId: '4', answer: 'Trong Javascript sự kiện OnUnload thực hiện khi', isCorrect: false },
  { _id: '6', questionId: '4', answer: 'Trong Javascript sự kiện', isCorrect: false },
  { _id: '7', questionId: '4', answer: 'Trong Javascript sự kiện OnUnload', isCorrect: false },
  { _id: '8', questionId: '4', answer: 'Trong Javascript', isCorrect: true },
];
