export const answer = [
  { _id: '1', questionId: '1', answer: 'Test avafsa' },
  { _id: '2', questionId: '1', answer: 'Test avafsa asdasd' },
  { _id: '3', questionId: '1', answer: 'Test 65321' },
  { _id: '4', questionId: '1', answer: 'Test avitoi' },
  { _id: '5', questionId: '2', answer: 'Trong Javascript sự kiện OnUnload thực hiện khi' },
  { _id: '6', questionId: '2', answer: 'Trong Javascript sự kiện' },
  { _id: '7', questionId: '2', answer: 'Trong Javascript sự kiện OnUnload' },
  { _id: '8', questionId: '2', answer: 'Trong Javascript' },
  { _id: '1', questionId: '3', answer: 'Test avafsa' },
  { _id: '2', questionId: '3', answer: 'Test avafsa asdasd' },
  { _id: '3', questionId: '3', answer: 'Test 65323' },
  { _id: '4', questionId: '3', answer: 'Test avitoi' },
  { _id: '5', questionId: '4', answer: 'Trong Javascript sự kiện OnUnload thực hiện khi' },
  { _id: '6', questionId: '4', answer: 'Trong Javascript sự kiện' },
  { _id: '7', questionId: '4', answer: 'Trong Javascript sự kiện OnUnload' },
  { _id: '8', questionId: '4', answer: 'Trong Javascript' },
];
